### ISSUE TITLE
it doesnt build with wlroots 0.15.1

### ISSUE THREAD

**Issue by adcdam** [riverwm/river#583]
with wlroots 0.15 build fine but fail with wlroots 0.15.1. 
i tested with a already built binary and wlroots 0.15.1 and it river work, but if i want to build it with wlroots 0.15.1 it fail to build.

**Comment by novakne** [comment]
What are the errors? Because it should builds without any problem with wlroots 0.15.1

**Comment by adcdam** [comment]
i got this:
```
./deps/zig-wlroots/src/wlroots.zig:174:9: error: zig-wlroots requires wlroots version 0.15
        @compileError("zig-wlroots requires wlroots version 0.15");
        ^
river...The following command exited with error code 1:
/usr/bin/zig build-exe /tmp/SBo/river-0.1.3/river/main.zig -lc -levdev -linput -lwayland-server -lxkbcommon -lpixman-1 -lwlroots -cflags -std=c99 -O2 -- /tmp/SBo/river-0.1.3/river/wlroots_log_wrapper.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/xdg-shell-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/pointer-gestures-unstable-v1-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/xdg-output-unstable-v1-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/pointer-constraints-unstable-v1-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/river-control-unstable-v1-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/river-status-unstable-v1-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/river-layout-v3-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/wlr-layer-shell-unstable-v1-protocol.c -cflags -std=c99 -- /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/wlr-output-power-management-unstable-v1-protocol.c -OReleaseSafe --cache-dir /tmp/SBo/river-0.1.3/zig-cache --global-cache-dir /home/dami/.cache/zig --name river --pkg-begin build_options /tmp/SBo/river-0.1.3/zig-cache/options/3blJUasGaRu56HGi5zh-8dov4FBLjD__Mg0_WsA7NOKmnvlpocSCrsSozsOSPI6s --pkg-end --pkg-begin wayland /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /tmp/SBo/river-0.1.3/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /tmp/SBo/river-0.1.3/deps/zig-pixman/pixman.zig --pkg-end --pkg-begin wlroots /tmp/SBo/river-0.1.3/deps/zig-wlroots/src/wlroots.zig --pkg-begin wayland /tmp/SBo/river-0.1.3/zig-cache/zig-wayland/wayland.zig --pkg-end --pkg-begin xkbcommon /tmp/SBo/river-0.1.3/deps/zig-xkbcommon/src/xkbcommon.zig --pkg-end --pkg-begin pixman /tmp/SBo/river-0.1.3/deps/zig-pixman/pixman.zig --pkg-end --pkg-end --pkg-begin flags /tmp/SBo/river-0.1.3/common/flags.zig --pkg-end -I /usr/include/libevdev-1.0 -I /usr/include/pixman-1 -I /usr/include/libdrm -I /usr/include/pixman-1 -I /usr/include/elogind --enable-cache 
error: the following build command failed with exit code 1:
/tmp/SBo/river-0.1.3/zig-cache/o/3eebbe56ce4947f5b913b147aa3bcd2a/build /usr/bin/zig /tmp/SBo/river-0.1.3 /tmp/SBo/river-0.1.3/zig-cache /home/dami/.cache/zig install -Drelease-safe -Dxwayland -Dman-pages --prefix /usr



```

**Comment by ifreund** [comment]
that check does not check the path version, it will match both `0.15.0` and `0.15.1`. You either have an outdated wlroots version or wlroots master installed.

**Comment by adcdam** [comment]
Thanks i reinstalled wlroots 0.15.1 and now it built fine, its strange all was sorking ok until i installed wayfire, sorry to bother! chose this.
best regards!

**Comment by ifreund** [comment]
No problem!
