### ISSUE TITLE
Errors while building (Gentoo + portage)

### ISSUE THREAD

**Issue by BurnyLlama** [riverwm/river#549]
I am trying to install river via portage (Gentoo's package manager), but I get the following errors:

```
/var/tmp/portage/gui-wm/river-0.1.3/work/river-0.1.3/deps/zig-wlroots/src/types/pointer_constraints_v1.zig:13:32: error: unable to override alignment of packed struct fields                               region: bool align(@alignOf(u32)) = false
/var/tmp/portage/gui-wm/river-0.1.3/work/river-0.1.3/deps/zig-wlroots/src/types/keyboard.zig:18:27: error: unable to override alignment of packed struct fields shift: bool align(@alignOf(u32)) = false
```

What does this mean? How do I fix it?

(I believe I am compiling straoght from the main branch.)

**Comment by novakne** [comment]
It seems like you're not using zig 0.9

**Comment by BurnyLlama** [comment]
`zig version` returns `0.10.0-dev.974+bf6540ce5`

Is zig 0.10 *bad* or should it work?

**Comment by novakne** [comment]
River always use the latest stable version of zig, so you can't use zig 0.10 which is the master branch. You can only use zig 0.9

**Comment by BurnyLlama** [comment]
I see! Does it matter if it is zig 0.9 or 0.9.1? Because the build file for Gentoo specifies the version 0.9.1 (which isn't available)...

**Comment by BurnyLlama** [comment]
Update: It worked with zig 0.9. Thanks for the help! :D

**Comment by novakne** [comment]
Last number in zig version is always bug fixes releases there is no breaking changes so 0.9.0 or 0.9.1 is fine. Obviously the one with bug fixes is better though.
